// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import Components__DropdownsController from "./components/dropdowns_controller"
application.register("components--dropdowns", Components__DropdownsController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import LoginMethodController from "./login_method_controller"
application.register("login-method", LoginMethodController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PhoneController from "./phone_controller"
application.register("phone", PhoneController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
